services:
  nginx-proxy:
    image: jwilder/nginx-proxy:1.7
    container_name: proxy
    hostname: proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      docker-net:
        ipv4_address: 10.10.1.4
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - nginx_logs:/var/log/nginx

  letsencrypt:
    image: nginxproxy/acme-companion:2.5
    container_name: ssl
    hostname: ssl
    restart: always
    networks:
      docker-net:
        ipv4_address: 10.10.1.5
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    volumes_from:
      - nginx-proxy
    environment:
      - NGINX_PROXY_CONTAINER=proxy
      - DEFAULT_LETSENCRYPT_EMAIL=lflores@okamistack.com

volumes:
  certs:
    external: true
  confd:
    external: true
  vhostd:
    external: true
  html:
    external: true
  dhparam:
    external: true
  nginx_logs:
    external: true
  acme:
    external: true

networks:
  docker-net:
    external: true
