services:
  wp:
    image: wordpress:6.7.2-php8.2
    container_name: wordpress
    restart: always
    hostname: wordpress
    networks:
      docker-net:
        ipv4_address: 10.10.1.3
    ports: #nos sirve para exportar los puertos del contenedor
      - 8080:80
    volumes:
      - wp_data:/var/www/html
      - /var/lib/docker/volumes/files/config/php.ini:/var/www/html/php.ini:ro
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/wp_passwd
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DEBUG=1 #nos permite poder imprimir cualquier error de wordpress
    secrets:
      - wp_passwd

secrets:
  wp_passwd:
    file: /var/lib/docker/volumes/files/secrets/wp_passwd

networks:
  docker-net:
    external: true

volumes:
  wp_data:
    external: true
